apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model-api
  template:
    metadata:
      labels:
        app: model-api
    spec:
      containers:
      - name: model-api
        image: ketanupadhyay/model-api:v1
        ports:
        - containerPort: 5000
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: model-api-service
spec:
  selector:
    app: model-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort

