name: Build and Deploy Model API

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Debug Secret Output (Do NOT use in real CI)
  run: |
    echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}"
    echo "DOCKER_TOKEN=${{ secrets.DOCKER_TOKEN }}" | wc -c

      - name: Build and Push Docker Image
        run: |
          docker build -t ketanupadhyay/model-api:v1 ./model-api
          docker push ketanupadhyay/model-api:v1

